/** Shared intent across creation, live content and polish; no genre or content-count quota. */
export const gameplayDepthGuidance = `PLAY VALUE BEFORE CONTENT VOLUME. Preserve the game's core appeal and make supported decisions more interesting.
Choose the next content for a specific player experience: learning a useful interaction, adapting an established strategy, making a tradeoff, expressing skill, investigating a clue, or seeing a meaningful consequence. More enemies, weapons, dialogue or systems are not goals by themselves.
For each substantial addition, identify what the player can now perceive/decide/do differently, what makes the choice situational, and how its consequence becomes visible. Prefer interactions and recombinations of existing rules before adding another system. A new enemy can matter through timing, position, cooperation or counterplay; a new weapon through commitment, range, resource use or interactions. These are examples, not required genres or a checklist.
Use supplied observations and player choices when present. If one tactic dominates, create fair supported situations that make another tactic useful without arbitrarily invalidating the player's build. If the player is struggling or still learning, allow rehearsal, recovery and payoff; novelty is not mandatory in every room. Absence of telemetry is not evidence of boredom, mastery or preference. Do not infer intent from one action or secretly change advertised rules to force variety.
Keep a coherent progression of understanding, agency and consequences. A satisfying familiar encounter is better than incoherent novelty. Alternate meaningful development with consolidation and resolution when appropriate; avoid endless escalation, grind or introducing more unresolved threads than the game can pay off.
Evaluate richness by changed decisions and interactions in play, not content counts or renamed/stat-inflated variants. Never sacrifice readability, fairness, responsiveness or the core appeal to meet a novelty target.`;

export const authorGameplayDepthGuidance = `${gameplayDepthGuidance}
During first-version creation, establish the core appeal in concise ordinary design notes: what the player repeatedly enjoys, the decisions that support it, and what would undermine it. Build a playable development of that core beyond the opening demonstration, without waiting for optional polish. Do not force monster, weapon, quest or system counts.
Audit the actual code and content schema for expressive capacity. Map each intended meaningful variation to implemented behavior, telegraphs, feedback, asset IDs and state transitions. If all future content can change is names, positions, counts or HP, improve the authoring-time behavior/data interfaces needed by THIS game before claiming rich continuation. Prefer reusable composable behaviors and interactions over hardcoded one-off variants. Assets and labels alone do not add mechanics.
In design/runtime.md, capture the core appeal, supported interaction vocabulary, the purpose of likely developments, pacing and fairness constraints, and consequences that must persist. Use examples to demonstrate expressive range, not to prescribe a fixed sequence forever. Pass compact observed play context when available: recent objectives, available actions/build, actions actually used, outcomes, repeated encounters and unresolved consequences. This uses the existing request context/save API; telemetry collection is not automatic. Keep observations distinct from interpretations and preserve privacy and bounded context.
Play beyond the opening encounter. Revisit the strongest tactic in a later situation, try a viable alternative, and exercise a consequence or payoff. Explain the changed decision and actual result. Check both repetitiveness and over-complexity; simplify or remove additions that do not improve play. If the schema/runtime prevents meaningful development, identify and fix that authoring gap instead of generating cosmetic variations or promising unsupported live code generation.
Runtime workers may only use implemented mechanics and valid fields; they do not edit running code, acquire arbitrary new assets or secretly change core rules. Evolve those capabilities during creation/polish, then verify the resulting continuation contract and save compatibility. Simulated success and source inventories are not evidence that humans find the game fun.`;
